make forbid-only as default on CI(#3030)
mochajs/mocha pull request #3987
Opened 2019-08-16 08:11 UTC by JaeHyeonKim19

### Description of the Change

* When `process.env.CI` is true, `forbid-only : true` is default value. And I changed one of conditional statements in `package-scripts.js` to keep its function.

### Alternate Designs

* There're may be a better way, but it's my best. 😂

### Why should this be in core?

* Due to this change, We can prevent pushing to remote repo with `.only`.

### Benefits

* Due to this change, We can prevent pushing to remote repo with `.only`.

### Possible Drawbacks

* If this change apply to mocha, Existing users can be confused. Because project which use '.only' on purpose gonna make conflict on CI. So We've to announce about this change when this change is applied.

### Applicable issues

* close #3030

2019-08-17 02:49 UTC, outsideris commented
Tests which use a fixture that has `.only` are failed. In Ci, we should handle this.

2019-11-12 08:00 UTC, JaeHyeonKim19 commented
Any review😂?

2023-12-02 21:13 UTC, JoshuaKGoldberg commented
👋 coming back to this @JaeHyeonKim19, are you still interested in working on this PR? As of https://github.com/mochajs/mocha/issues/5027 there are again maintainers who can review it now. No worries if you no longer have time - but if you do that'd be great!

_(I do see that your last message was asking for review - unless directed otherwise try to review it once we're ramped up enough!)_

2024-03-01 16:42 UTC, JoshuaKGoldberg requested changes
The functional default value change looks good to me! Requesting changes I'm not sold on the `--no-forbid-only`, and would like to see docs. Thanks! 🙌 

(if you don't have time for this, we'll go ahead and send a new PR after a while)

2024-03-01 16:42 UTC, JoshuaKGoldberg commented on package-scripts.js
> +      mochaParams += ' --no-forbid-only';
[Question] 🤔 Is `--no-forbid-only` necessary? My interpretation of https://github.com/mochajs/mocha/issues/3030#issuecomment-333044369 was that the issue can be resolved with just the change to `forbid-only`'s default value.

2024-03-01 16:42 UTC, JoshuaKGoldberg commented on lib/cli/run.js
[Docs] https://mochajs.org/#-forbid-only should be updated to mention this, too. Folks will want to know if the default value isn't always falsy.

2024-07-02 16:49 UTC, closed without merging