Fix mocha return interface #4286
mochajs/mocha pull request #4429
Opened 2020-08-30 04:51 UTC by MoonSupport

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change

`mocha.run` return `{Runner: runner, Promise<Test[]>}`

To be precise, `runner.run` return this.

### Alternate Designs

Before
mocha.run() : runner

After
mocha.run() : {Runner: runner, Promise<Test[]>}

### Why should this be in core?

https://github.com/mochajs/mocha/issues/4286

### Benefits

It can provide an easier interface to consumers running Mocha programmatically.

### Possible Drawbacks

I was careful because it was a modification of the interface of the core function.

the callback is deprecated, but it couldn't be deleted for existing users using callback.
And I think it could be a bit slow in the process of putting the tests into an array.
Finally, since I don't have enough background on Mocha, I desperately need your help to prevent side-effect.

### Applicable issues

https://github.com/mochajs/mocha/issues/4286

2020-09-02 19:44 UTC, boneskull requested changes
Thanks for this!

So, while the function itself is weird, I think maybe it's unwise to change the API of `Mocha.prototype.run`, as I suggested in #4286.  Maybe better to expose a new method, e.g., `Mocha.prototype.runAsync`.  PR #4360 adds a `Runner.prototype.runAsync` method, which would work nicely in tandem with a `Mocha.prototype.runAsync`.

My advice is to wait until #4360 lands (likely very soon), then:

1. Create method `Mocha.prototype.runAsync`
1. Either this method will _wrap_ `Mocha.prototype.run` _or_ extract common behavior into a third private method, e.g., `Mocha.prototype._run()` and call `_run()` from both places.
1. Update usages of `Mocha.prototype.run` to use `Mocha.prototype.runAsync` instead
1. Copy unit tests for `Mocha.prototype.run` and assert they work against the new `Promise`-returning API
1. Also: don't forget `mocha.run()` in `browser-entry.js`.  Run browser tests in headless Chrome via `npm start test.browser`

At that point, we can decide if `Mocha.prototype.run()` should be deprecated.  I'm thinking the impact of removing it would outweigh the burden of keeping it around, even if we don't use it internally.

2020-09-02 19:48 UTC, boneskull commented
Once this is done, please mark this PR as "ready"; I've converted it to a draft

2020-09-03 11:33 UTC, MoonSupport commented
Good!
I'll wait while checking it!

2020-09-12 13:28 UTC, MoonSupport commented
Hello!
I adjusted your update.
However, in the parallel mode, there is a problem with the test, so in this case, it operates as before.
The stack seems to be full, but I don't know the exact cause.

Sorry for not being able to help 😫

2020-10-12 21:58 UTC, boneskull reviewed
thanks.  I'm not sure I understand what the problem is that you're describing... but the changes to `Runner.prototype.run` aren't making sense to me.  

if this helps: in parallel mode, Mocha uses `ParallelBufferedRunner` which is in `lib/nodejs/parallel-buffered-runner.js`.  this is a subclass of `Runner`.  _only_ the _main process_  uses `ParallelBufferedRunner`.  each worker process in the pool will invoke its own Mocha and use `Runner`.  the `Mocha` instance in the worker process does not necessarily know or care if it is in parallel mode.

are you interested in working on this further?

2020-10-17 12:39 UTC, MoonSupport commented
I don't have enough time to watch this problem right now. but if you leave this pr, I'll be able to see it later :) 
I still want to do it, but it's okay to close it.

2020-11-02 22:21 UTC, boneskull commented
Feel free to reopen later

2020-11-02 22:21 UTC, closed without merging