Change deprecated methods in assert library
mochajs/mocha pull request #4435
Opened 2020-09-02 10:50 UTC by sujin-park

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change

I removed deprecated methods and tested it. ```equal, deepEqual``` methods are deprecated since v.9.9.0. [Assert Reference](https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message)

I used ```strictEqual, deepStrictEqual``` instead.

### Alternate Designs

**deprecated**
```javascript
assert.equal(getTitle(this), undefined);
assert.deepEqual(sock.address().family, 'IPv4');
```

**changed**

```javascript
assert.strictEqual(getTitle(this), undefined);
assert.deepStrictEqual(sock.address().family, 'IPv4');
```

For now, PR's just changed methods that was deprecated. I wonder if i can change code using unexpected library as shown below. I found [this issue](https://github.com/mochajs/mocha/pull/3343) about migrating assert to Unexpected assertion library.  I wonder if there are still ```assert``` left.

**assert**
```javascript
assert.strictEqual(getTitle(this), undefined);
assert.deepStrictEqual(sock.address().family, 'IPv4');
```

**unexpected assertion library**
```javascript
expect(getTitle(this), 'to be', undefined);
expect(sock.address().family, 'to equal', 'IPv4');
```

### Why should this be in core?

N/A

### Benefits

Users can view the modified version of the function within code.

### Possible Drawbacks

N/A

### Applicable issues

patch release

2020-09-02 13:29 UTC, sujin-park commented
I'm working on test cases 😢

2020-09-02 19:48 UTC, boneskull commented
Please mark this PR as ready when ready.  I know there's at least _one_ place in our tests that must use `assert`.

2020-09-10 09:54 UTC, sujin-park commented
Thank you for your feedback.
I modified 2 test files including diff tests. When using strictEqual, deepStrictEqual function instead of strictEqual, deepEqual with node version of 10, tests failed because inline diff outputs twice from AssertionError.

<img width="824" alt="스크린샷 2020-09-10 오후 6 50 15" src="https://user-images.githubusercontent.com/29244798/92714103-baa15280-f396-11ea-8b35-dd5c3878a575.png">

I modified diffs.spec.js so that only one of the two outputs can be printed. also i changed ```should not display a diff``` 
test to skip when node version is 10. It should be removed when Node.js 10 LTS is not supported.

Please let me know what needs to be modified. Thanks! I marked this PR.

2020-09-25 21:47 UTC, boneskull requested changes
Thanks.  I think maybe better to just detect Node.js v10.x and skip the tests.  So revert the changes to `test/integration/diffs.spec.js` and use the same strategy as in `test/integration/no-diff.spec.js`. do it in a `before()` hook within the top-level `describe()`.

it's worth mentioning (in the docs, maybe?) that Mocha's "no diff" behavior does not work if the diff is embedded in the `message` prop of an `Error`.

2020-10-13 12:46 UTC, sujin-park commented
> Thanks. I think maybe better to just detect Node.js v10.x and skip the tests. So revert the changes to `test/integration/diffs.spec.js` and use the same strategy as in `test/integration/no-diff.spec.js`. do it in a `before()` hook within the top-level `describe()`.

I reverted the changes to test/integration/diffs.spec.js and use skip tests in the file as in test/integration/no-diff.spec.js.

> it's worth mentioning (in the docs, maybe?) that Mocha's "no diff" behavior does not work if the diff is embedded in the `message` prop of an `Error`.

I'm considering mentioning [this part of the docs](https://mochajs.org/#-diff) that you told, so can I proceed with it in another PR? please let me know if it's okay to proceed like that. Thank you for your comments.

2020-10-30 18:59 UTC, boneskull approved these changes

2020-10-30 18:59 UTC, boneskull commented
lgtm, thanks

2020-10-30 19:00 UTC, merged