refactor: utils.type()
mochajs/mocha pull request #4457
Opened 2020-10-01 20:37 UTC by ValeriaVG

## Description of the Change
- Existing `utils.type()` is renamed to `utils.canonicalType()`
- Call from `utils.canonise()` is changed to `canonicalType()`
- New function `type()`added to the `utils` implementing generic type retrieval based on [MDN:DataStructures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures) and several additional cases: Error => 'error' and String = > 'string', aiming to replace `Array.isArray()`, `typeof` and `Buffer.isBuffer`.

### Alternate Designs
Diff functionality, as suggested in the related issue, should be separated in its own module. 
The only difference is that this PR implies incremental changes.

An alternative could be to instead implement `isType(value, type)` due to the use intentions.

### Why should this be in core?
- It is part of the core functionality

### Benefits
- Lays foundation for future `utils` refactoring
- Adds ability to perform strict and generic type comparisons
- 

### Possible Drawbacks
- The only file that uses new `utils.type()` is `lib/node/serializer.js`

### Applicable issues
https://github.com/mochajs/mocha/issues/4306

2020-10-02 21:45 UTC, boneskull requested changes
Thanks!  Looks really good.  Just had a couple comments.  "Modern" ES syntax is now usable throughout the codebase, so that should simplify/improve some of the changes here.

2020-10-02 21:45 UTC, boneskull commented on lib/utils.js
> +  var primitives = [
you can use a `Set` here.

2020-10-02 21:45 UTC, boneskull commented on lib/runner.js
> +    'the ' +
you can use a template literal here

2020-10-02 21:45 UTC, boneskull commented on lib/nodejs/serializer.js
> +    if (type(value) === 'error') {
good

2020-10-02 21:45 UTC, boneskull commented on lib/utils.js
> +exports.type = function type(value) {
This should be marked `@private` unless there's reason to make it public

2020-10-03 06:13 UTC, ValeriaVG commented
Thank you, makes total sense.
Changes made:
- `utils.type()` now uses `Set` instead of an array and `const` instead of `var`
- `runner.thrown2Error()` now uses template literal
- `serializer._serialize()` now stores computed type value and explicitly sets it to `object`, when Error is being transformed to an object

2020-10-09 19:22 UTC, boneskull approved these changes
LGTM! tyvm

2020-10-09 19:23 UTC, merged