Closes #4548
mochajs/mocha pull request #4549
Opened 2021-01-11 08:21 UTC by ctjlewis

Use `path.resolve` to ensure that `require.resolve` is only passed absolute filepaths.

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change
`unloadFile` is only ever passed paths to files, but relative paths cause `MODULE_NOT_FOUND` when imported in an ESM context. Ensuring that `unloadFile` is only ever called with absolute filepaths prevents this.

### Applicable issues
#4548

2021-01-11 09:17 UTC, juergba commented
@ctjlewis thank you
I did some changes to our CI test workflow yesterday. I don't know why the `pull-request` event hasn't triggered our CI tests on your PR. I need to get this solved first.

2021-01-11 09:18 UTC, ctjlewis commented
No worries @juergba, I was looking for CI tests as well. I will pull from upstream when that's settled, just ping me here, no rush.

2021-01-11 10:29 UTC, juergba commented
So, I have two problems with the workflow:
I don't know your branch's name from your fork. It's not `unload-files`, nor `ctjlewis:unload-files`, nor `ctjlewis/mocha:unload-files`. I need to distinguish PR's coming from a fork against pushed ones to the original mocha repo.

Browser test: 
The github [docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories) says: 
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

I guess thats the reason, why the browser test is failing. The SaucLabs login doesn't work.
Do you have any idea?

2021-01-11 10:32 UTC, ctjlewis commented
GitHub embeds it here as `ctjlewis/mocha:unload-files`. 

![image](https://user-images.githubusercontent.com/1657236/104169975-035d2c80-53c6-11eb-9fa6-3f502d4ee842.png)

I have no idea about the CI - I've never contributed to Mocha before, I just ran into this error and wanted to submit a patch.

2021-01-11 13:24 UTC, juergba commented
The CI tests do run now on your PR, but the browser test will fail most propably.
I will have to investigate further on that one.

You could rebase locally and force-push to your fork, if you want.
Thanks for letting me abuse your PR.

2021-01-12 00:23 UTC, ctjlewis commented
No worries @juergba, feel free to use this PR to debug.

2021-01-13 06:27 UTC, ctjlewis commented
@juergba Hey, any way I can help out here? This bug does actually break most `unloadFiles()` calls in ES contexts - not trying to be pushy at all, but I'm happy to help move it along any way I can. This was the fastest response to a PR I've ever had (1hr) so I'm not complaining by any means.

2021-01-13 14:21 UTC, juergba commented
@ctjlewis If I remember correctly, the ESM loader doesn't use the `require` cache.

see our [API - unloadFiles](https://mochajs.org/api/mocha#unloadFiles)
see [Node docs](https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_no_require_cache)

Even worse, AFAIK there is no way to clear the ESM cache. E.g. that's why our `watch` functionality doesn't work with ESM. There is no way to clear the cache and re-run the tests.
BTW `unloadFile` is a private function.

2021-01-13 19:35 UTC, ctjlewis commented
This PR fixes the issue. And yes but `unloadFiles`, which relies
`unloadFile`, is public.

I ran into this issue in real-world codebase, and resolving the import path
works. Mocha is imported as a CJS module so `require` works as expected
inside Mocha’s source, it can be safely ignored.

On Wed, Jan 13, 2021 at 8:22 AM Juerg B. <notifications@github.com> wrote:

> @ctjlewis <https://github.com/ctjlewis> If I remember correctly, the ESM
> loader doesn't use the require cache.
>
> see our API - unloadFiles <https://mochajs.org/api/mocha#unloadFiles>
> see Node docs
> <https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_no_require_cache>
>
> Even worse, AFAIK there is no way to clear the ESM cache. E.g. that's why
> our watch functionality doesn't work with ESM. There is no way to clear
> the cache and re-run the tests.
> BTW unloadFile is a private function.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mochajs/mocha/pull/4549#issuecomment-759480080>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMUTFA3GRTV6U63N5W4NL3SZWUA5ANCNFSM4V5GQ62A>
> .
>

2021-01-14 15:42 UTC, juergba commented
I'm not convinced of this change. I will need a few days to look into it more closely.

Your examples just don't make any sense:
  - you never load any test files, neither the ESM way via `loadFilesAsync`, nor the CommonJS way via `mocha.run` (which calls `loadFiles`). The function `loadFiles` does call `path.resolve`.
  - `unloadFiles` does not clear the ESM cache (which is not the `require.cache`).

2021-01-14 22:13 UTC, ctjlewis commented
I guess the issue is not as obvious as I thought - I made a Repl.it here: https://repl.it/@christiantjl/MochaRequireResolve

This basically only affects programs where we import Mocha from an ESM context. ES modules *can* import CJS modules, and that `require.resolve` statement is executed within the emulated CJS module. I think under the hood it relies on `import.meta.resolve` but since Mocha is a CJS module, this is the appropriate fix, which adds support for ES interoperation.

I should have made it clear this is an ESM interop thing, where, for CJS programs, this will have no impact, but it will prevent this error from presenting when Mocha is used programmatically from inside an ES module via `import Mocha from 'mocha'`.

Apologies for not including a repro off the bat.

2021-01-15 02:04 UTC, ctjlewis commented
Tfw I *did* include a repro in that issue, and I basically recreated it a second time... I hope I have sufficiently demonstrated the issue lmao.

2021-01-17 22:59 UTC, ctjlewis commented
Hate to bug you @juergba, but did you have a chance to review the example?

2021-01-19 17:04 UTC, juergba commented
@ctjlewis None of your repros works, there are syntax errors all over when pressing the Run-Button.

Meanwhile I doubt that this issue has its cause specifically with ESM. If you just take following code snippet:
```js
mocha.addFile('./test/test-pending.js');
console.log(require.resolve('./test/test-pending.js', {paths:[process.cwd()]}));     // runs successfully
console.log(require.resolve('./test/test-pending.js'));                              // fails
```
The module resolution algorithm does not include sub-directories of the current working directory. Therefore `require.resolve` fails.

Since `loadFiles` calls `path.resolve`, it could make sense to do the same in `unloadFiles` as well.

2021-01-19 19:39 UTC, ctjlewis commented
The run button doesn't work because of the Node version Repl.it uses. Execute `node index.js` to show the behavior of `succeeds.js` and `fails.js`.

I am admittedly getting frustrated because you keep trying to tell me that this error is not real simply because you are struggling to understand it. I have tried to explain this multiple times: This presents when Mocha is imported as a CJS module in an *ESM context*.

Switch over to the shell tab, and run `node index.js` to execute the two tests.

2021-01-19 19:43 UTC, ctjlewis commented
CC:
@boneskull
@craigtaub
@Munter
@outsideris

2021-01-19 20:52 UTC, ctjlewis commented
I updated the Repl.it with a custom environment and all `.mjs` extensions to get the repro to work with the Run button rather than needing to execute it directly:

https://repl.it/@christiantjl/MochaRequireResolve

2021-06-04 00:48 UTC, closed without merging

2024-01-15 06:18 UTC, JoshuaKGoldberg commented
Looks like this was not stale, and the author did provide a good amount of repro steps. Re-opening & marking the issue as accepted.

2024-01-15 06:32 UTC, ctjlewis commented
> Looks like this was not stale, and the author did provide a good amount of repro steps. Re-opening & marking the issue as accepted.

Yeah, this was one of the most incompetent responses to a bugfix PR I'd ever seen in my life. It's one thing to handle a bug report like shit, but it's especially sad when contributors are your hand and submit a fix alongside the report, plus various repros.

That guy owes me an apology. Plus everyone who uses Mocha for forcing a bug to stay in the library for 3 years.

2024-03-04 13:08 UTC, JoshuaKGoldberg requested changes
Seems reasonable, thanks! But we'll want to unit test this.

2024-03-04 13:08 UTC, JoshuaKGoldberg commented on lib/nodejs/file-unloader.js
[Testing] This change seems reasonable at first glance, but we'll want to have unit tests for it. Do you see a way to do that?

2024-07-02 16:53 UTC, JoshuaKGoldberg commented
👋 ping @ctjlewis, is this still something you have time for?

2024-08-06 15:14 UTC, JoshuaKGoldberg commented
Closing out as it's been a while since PR activity. If anybody wants to take this over, please do - and post a co-author attribution if you take code from this PR. Cheers! 🤎