chore: bump chokidar to ^3.6.0
mochajs/mocha pull request #5143
Opened 2024-05-16 08:02 UTC by simhnna

Fixes: #5142

## PR Checklist

- [x] Addresses an existing open issue: fixes #5142
- [ ] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md) were taken

## Overview

Compatibility with newer @types/node releases for typescript users

2024-05-21 00:29 UTC, legobeat commented on package.json
> +    "chokidar": "^3.6.0",
Mocha is pinning to exact versions in manifest by convention. While I'd also suggest reconsidering that decision, changing that probably doesn't belong in this PR @simhnna?

```suggestion
    "chokidar": "^3.6.0",
```

2024-05-21 00:29 UTC, legobeat commented on package-lock.json
> +        "chokidar": "^3.6.0",
```suggestion
        "chokidar": "3.6.0",
```

2024-05-21 12:35 UTC, legobeat commented on package.json
> +    "chokidar": "^3.6.0",
Sorry, I missed the context there!

2024-05-24 09:42 UTC, JoshuaKGoldberg requested changes
Thanks for this! Up for switching to `^` and having this target the `chokidar` part of #5114?

2024-05-24 13:01 UTC, JoshuaKGoldberg commented
I also tried an `npm upgrade chokidar` locally and re-running tests and such. They all worked. ✔️

2024-05-24 13:01 UTC, merged

2024-06-24 18:00 UTC, JoshuaKGoldberg commented
This was released in [`mocha@10.5.0`](https://www.npmjs.com/package/mocha/v/10.5.0). 🚀