docs: update README, LICENSE and remove outdated
mochajs/mocha pull request #5197
Opened 2024-08-09 11:24 UTC by voxpelli

* Fixes the test badge
* Updates some copyright years
* Removes saucelabs and fossa embeds
* Uses local logo rather than logo from unknown CDN
* Reorders badges so that package related badges are on the top and community related ones below

2024-08-14 00:29 UTC, JoshuaKGoldberg commented on docs/README.md
This is still useful though, `npm run docs(-watch)` is what I've been using to run the site.

2024-08-14 00:29 UTC, JoshuaKGoldberg commented on README.md
> +</div>
[Praise] _Yes_ big +1 on the reordering & fixing up. This was bugging me.

2024-08-14 00:30 UTC, JoshuaKGoldberg requested changes
Root-level `README.md` looks great to me, but the `docs/` one I still use?

2024-08-21 16:15 UTC, voxpelli commented on docs/README.md
@JoshuaKGoldberg It felt extremely out of date, mentioning wrong node.js support + mentioning the JS Foundation rather than the OpenJS Foundation

2024-08-21 16:21 UTC, JoshuaKGoldberg commented on docs/README.md
👍 up for just removing those outdated bits? Or at least just leaving in a little bit?

2024-08-21 16:32 UTC, voxpelli commented on docs/README.md
@JoshuaKGoldberg Done ✔️

2024-08-21 18:06 UTC, JoshuaKGoldberg approved these changes
📝🚀

2024-08-21 19:00 UTC, merged