docs: add new website using Astro Starlight
mochajs/mocha pull request #5246
Opened 2024-11-06 18:25 UTC by JoshuaKGoldberg

## PR Checklist

- [x] Addresses an existing open issue: fixes #5065; fixes #5207
- [x] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Creates a new website under `docs-next/` using [Astro Starlight](https://starlight.astro.build). It contains roughly the same documentation as before, just split up into a more modern website with a navigation sidebar and a table-of-contents on each page. Its base route is `next/`, like https://mochajs.org/next.

"Feature parity" tasks that I took to generate this

- [x] Set up site on a `/next` base URI
- [x] Create visual theme based on the existing brand colors
  - Port over the top-of-page animated logo
  - Port over the footer
- [x] Separate existing headings and content into structured content
  - [x] Reorder cli.mdx to match actual CLI output and sections
  - [x] Add new `interfaces/third-party` page to match `reporters/third-party`
- [x] Update inline links to use the new structure
- [x] Update block quotes and other emphasized lines to admonitions
- [x] Add build script to generate sponsors data

After this is merged, we'll want to:

1. Deploy this on mochajs.org/next, with existing routes such as `/api` not being impacted
2. Announce it out for early interest & feedback
3. Wait a while
4. Eventually switch this site to be the root page, with the old one under something like `/old`
   - Needed: JavaScript-based redirects for old `#` headings
   - Needed: Migrate the existing `/api` old JSDoc & docdash generation (or an equivalent)
   - Needed: Migrate the existing `/examples/test` page from the old docs
Later-on out-of-scope items that I think would be good:

- Fill in missing content
  - Move content from the wiki that should be here, such as third-party interfaces and reporters
  - Move mochajs/mocha/tree/main/example/config to the examples repo
- Refresh Editor Plugins
- Revamp the sponsors & backers lists to be more based on total donations
- Revamp the content to be more clear, organized, and up-to-date with modern practices
  - Stop discouraging arrow functions in features/arrow-functions
- Run an accessibility audit on link titles and image descriptions
- Update screenshots
- Update out-of-date information
  - Editor plugins, reporters
  - Screenshots of browsers
  - Third-party examples
- Update version notices older than 8.0.0 (see existing issue)
- Onboard `/api` to something new like TypeDoc
- 404 page

Astro/Starlight issues:

- **To be filed:** Suggest `ComponentProps<typeof Default>` in overriding components
- **To be filed:** Asides that are empty: don't add extra vertical interior margin

💖

2025-03-16 02:31 UTC, mark-wiemer requested changes
Looks pretty darn good!

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/interfaces/require.mdx
> +---
```suggestion
---
description: The require interface for Mocha.
title: Require
---
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/reporters/landing.mdx
> +description: The Landing test reporter for Mocha.
```suggestion
description: The Landing strip test reporter for Mocha.
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/reporters/markdown.mdx
> +This is great if you want to use the tests as documentation within a Github wiki page, or a markdown file in the repository that Github can render.
```suggestion
This is great if you want to use the tests as documentation within a GitHub wiki page, or a markdown file in the repository that GitHub can render.
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/reporters/xunit.mdx
> +It outputs an XUnit-compatible XML document, often applicable in CI servers.
```suggestion
The XUnit reporter outputs an XUnit-compatible XML document, often applicable in CI servers.
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/browsers.mdx
> +Mocha runs in the browser.
At a glance, this reads like Mocha only runs in the browser

```suggestion
Mocha can run in the browser.
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +Running `npx mocha --help` will show the full list of available commands:
Should we add a source comment linking this to the definition in code? I want to update some stuff here but want it to match released code too

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +      --pass-on-failing-test-suite  Not fail test run if tests were failed
```suggestion
      --pass-on-failing-test-suite  Don't fail test run if tests were failed
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +This behavior enables a set of potential problems; it's indicative of tests (or fixtures, harnesses, code under test, etc.) which don't clean up after themselves properly.
```suggestion
This behavior enables a set of potential problems: it's indicative of tests (or fixtures, harnesses, code under test, etc.) which don't clean up after themselves properly.
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +Fail test run if no tests are encountered with `exit-code: 1`.
Previous reading could be that a test needs an exit code

```suggestion
Fail test run with `exit-code: 1` if no tests are encountered.
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +Tests may be rerun manually by typing &#x24e1; &#x24e2; &#x23ce; (same shortcut as `nodemon`).
Why `ⓡ ⓢ ⏎` ?

```suggestion
Tests may be rerun manually by typing `rs` and pressing enter (same shortcut as `nodemon`).
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +Some shells as e.g. Git-Bash-for-Windows may require: `--grep "'/get/i'"`.
```suggestion
Some shells (e.g. Git Bash for Windows) may require: `--grep "'/get/i'"`.
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +:::note[New in vNode.js v12.12.0]
```suggestion
:::note[New in Node.js v12.12.0]
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +V8 flags can be defined in Mocha's [configuration](./configuring).
I thought this was Mocha v8 at first, was confused, a link might help. Couldn't find a link to an official flags list

```suggestion
[V8](https://v8.dev/) flags can be defined in Mocha's [configuration](./configuring).
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/configuring.mdx
> +See [here](http://yargs.js.org/docs/#api-reference-configobject-extends-keyword) for more information.
```suggestion
See [yargs API reference](http://yargs.js.org/docs/#api-reference-configobject-extends-keyword) for more information.
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/editor-plugins.mdx
> +
This guy was last updated in 2019, for now I think no recommendation is better than a bad recommendation. Personally I use VS Code without any Mocha-specific extensions so I don't have a replacement offhand

```suggestion
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/editor-plugins.mdx
> +![mocha side bar in Action](./mocha_side_bar.png)
```suggestion
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/mocha_side_bar.png
Delete unused image (per previous suggestion, mocha side bar hasn't been updated since 2019)

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/editor-plugins.mdx
> +description: Configuring how Mocha finds test files.
```suggestion
description: Configuring Mocha in an editor
```

2025-03-16 02:31 UTC, mark-wiemer commented on docs-next/src/content/docs/running/test-globs.mdx
> +See this [tutorial](https://gist.github.com/reggi/475793ea1846affbcfe8) on using globs.
```suggestion
See this [tutorial on using globs](https://gist.github.com/reggi/475793ea1846affbcfe8).
```

2025-03-17 13:47 UTC, JoshuaKGoldberg reviewed
Thanks so much for the thorough review @mark-wiemer!

For all the suggestions to Astro/infra areas and introduced issues: 👍 agreed, applied.

For the clarity, proofreading, and other existing content changes suggestions: I propose we tackle those in >1 followup PR. Some of them are more subjective and might take some time for discussion. I think it'd be valuable to get this PR merged in the interim. WDYT?

2025-03-17 14:01 UTC, JoshuaKGoldberg commented on docs-next/src/content/docs/running/editor-plugins.mdx
> +
I think this would be a good thing to do in a separate change. As with the other content changes:

* Discussion: I know there are other extensions out there, and we should probably discuss more deeply which -if any- should get the "official" mochajs.org blessing
* Trackability: so it's easier to see where things got CRUD-ed

2025-03-17 14:02 UTC, JoshuaKGoldberg commented on docs-next/src/content/docs/features/parallel-mode.mdx
> +- ✅ Look for root hooks (they look like [this](#root-hooks-are-not-global)) in your tests.
Strong agree on making the links accessible! ACK that this violates https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context. Accessibility changes in particular I try to split out into discrete PRs: oftentimes I'll later send those out as references when advocating for a11y improvements elsewhere!

2025-03-17 14:04 UTC, JoshuaKGoldberg commented on docs-next/src/content/docs/index.mdx
> +If you see any **bugs** or **typos** _that aren't on [mochajs.org](https://mochajs.org)_, please mention them on [docs: add new website using Astro Starlight](https://github.com/mochajs/mocha/pull/52
I was hoping to avoid cases where people report existing issues on this PR and feel disappointed if we opt to merge without fixing. Both for direct bugs and more amorphous _"this phrasing could be improved with a reorder"_ kind of longer-ended discussions... can you think of a better phrasing to encapsulate this?

2025-03-17 16:49 UTC, mark-wiemer commented on docs-next/astro.config.ts
> +      title: "Mocha",
consider this resolved per other thread, props are alphabetical as a canonical sort order

2025-03-17 16:50 UTC, mark-wiemer commented on docs-next/src/content/docs/declaring/inclusive-tests.mdx
> +Anything skipped will be marked as [pending](./pending-tests), and reported as such.
Mark as resolved, just proofreading

2025-03-17 16:50 UTC, mark-wiemer commented on docs-next/src/content/docs/declaring/inclusive-tests.mdx
> +_Note_: Code in skipped suites, that is placed outside of hooks or tests is still executed, as mocha will still invoke the suite function to build up the suite structure for visualization.
Mark as resolved, just proofreading

2025-03-17 16:50 UTC, mark-wiemer commented on docs-next/src/content/docs/declaring/pending-tests.mdx
> +Pending tests will be included in the test results, and marked as pending.
Mark as resolved, just proofreading

2025-03-17 16:50 UTC, mark-wiemer commented on docs-next/src/content/docs/declaring/retrying-tests.mdx
> +Example below was written using Selenium webdriver (which [overwrites global Mocha hooks](https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/javascript/node/selenium
Mark as resolved, just proofreading

2025-03-17 16:51 UTC, mark-wiemer commented on docs-next/src/content/docs/explainers/run-cycle-overview.mdx
> +   1. When a test file is loaded, Mocha executes all of its suites and finds--_but does not execute_--any hooks and tests therein.
Nice, must be a feature of Astro/MDX that I didn't know about. I saw `&mdash;` in some other places and wanted to be consistent, didn't think to check the rendered page, sorry! Consider this resolved

2025-03-17 16:51 UTC, mark-wiemer commented on docs-next/src/content/docs/explainers/test-fixture-decision-tree.mdx
> +This flowchart will help you decide which of [hooks], [root hook plugins](../features/root-hook-plugins) or [global fixtures](../features/global-fixtures) you should use.
Mark as resolved, just proofreading

2025-03-17 16:51 UTC, mark-wiemer commented on docs-next/src/content/docs/features/asynchronous-code.mdx
> +By adding an argument (usually named `done`) to `it()` to a test callback, Mocha will know that it should wait for this function to be called to complete the test.
Mark as resolved, just proofreading

2025-03-17 16:52 UTC, mark-wiemer commented on docs-next/src/content/docs/features/asynchronous-code.mdx
> +This callback accepts both an `Error` instance (or subclass thereof) _or_ a falsy value; anything else is invalid usage and throws an error (usually causing a failed test).
Mark as resolved, just proofreading

2025-03-17 16:52 UTC, mark-wiemer commented on docs-next/src/content/docs/features/hooks.mdx
> +Hooks will run in the order they are defined, as appropriate; all `before()` hooks run (once), then any `beforeEach()` hooks, tests, any `afterEach()` hooks, and finally `after()` hooks (once).
Mark as resolved, just proofreading

2025-03-17 16:52 UTC, mark-wiemer commented on docs-next/src/content/docs/features/parallel-mode.mdx
> +If parallel mode is defined in your config file, you can temporarily disable it on the command-line by using either the `--no-parallel` flag or reducing the job count, e.g., `--jobs=0`.\_
Mark as resolved, just proofreading

2025-03-17 16:52 UTC, mark-wiemer commented on docs-next/src/content/docs/features/parallel-mode.mdx
> +   of v8.0.0) [Root Hook Plugin](./root-hook-plugins) system.
Mark as resolved, just proofreading

2025-03-17 16:53 UTC, mark-wiemer commented on docs-next/src/content/docs/features/parallel-mode.mdx
> +- ✅ Look for root hooks (they look like [this](#root-hooks-are-not-global)) in your tests.
Works for me :)

2025-03-17 16:53 UTC, mark-wiemer commented on docs-next/src/content/docs/features/parallel-mode.mdx
> +That said, _play around with the job count_--there's no one-size-fits all, and the unique characteristics of your tests will determine the optimal number of jobs; it may even be that fewer is faster!
Unnecessary, sry, `--` is much easier to remember anyway

2025-03-17 16:53 UTC, mark-wiemer commented on docs-next/src/content/docs/features/root-hook-plugins.mdx
> +If you need to perform some logic--such as choosing a root hook conditionally, based on the environment--`mochaHooks` can be a _function_ which returns the expected object.
Unnecessary, sry, `--` is much easier to remember anyway

2025-03-17 16:53 UTC, mark-wiemer commented on docs-next/src/content/docs/features/root-hook-plugins.mdx
> +1. Find your root hooks (hooks defined _outside_ of a suite--usually `describe()` callback).
Unnecessary, sry, `--` is much easier to remember anyway

2025-03-17 16:54 UTC, mark-wiemer commented on docs-next/src/content/docs/features/root-hook-plugins.mdx
> +:::
This one is kinda important IMO for a quick followup, but otherwise: Mark as resolved, just proofreading

2025-03-17 16:57 UTC, mark-wiemer commented on docs-next/src/content/docs/reporters/xunit.mdx
> +It outputs an XUnit-compatible XML document, often applicable in CI servers.
Mark as resolved, just proofreading

2025-03-17 16:57 UTC, mark-wiemer commented on docs-next/src/content/docs/running/browsers.mdx
> +Mocha runs in the browser.
Mark as resolved, just proofreading

2025-03-17 16:57 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +Running `npx mocha --help` will show the full list of available commands:
Good candidate for a followup PR

2025-03-17 16:57 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +      --pass-on-failing-test-suite  Not fail test run if tests were failed
Mark as resolved, just proofreading

2025-03-17 16:57 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +This behavior enables a set of potential problems; it's indicative of tests (or fixtures, harnesses, code under test, etc.) which don't clean up after themselves properly.
Mark as resolved, just proofreading

2025-03-17 16:58 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +Fail test run if no tests are encountered with `exit-code: 1`.
Mark as resolved, just proofreading

2025-03-17 16:58 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +Tests may be rerun manually by typing &#x24e1; &#x24e2; &#x23ce; (same shortcut as `nodemon`).
Mark as resolved, just proofreading

2025-03-17 16:58 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +Some shells as e.g. Git-Bash-for-Windows may require: `--grep "'/get/i'"`.
Mark as resolved, just proofreading

2025-03-17 16:58 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +:::note[New in vNode.js v12.12.0]
Mark as resolved, just proofreading

2025-03-17 16:58 UTC, mark-wiemer commented on docs-next/src/content/docs/running/cli.mdx
> +V8 flags can be defined in Mocha's [configuration](./configuring).
Mark as resolved, just proofreading

2025-03-17 16:58 UTC, mark-wiemer commented on docs-next/src/content/docs/running/configuring.mdx
> +See [here](http://yargs.js.org/docs/#api-reference-configobject-extends-keyword) for more information.
Mark as resolved, just proofreading, good a11y candidate

2025-03-17 16:59 UTC, mark-wiemer commented on docs-next/src/content/docs/running/editor-plugins.mdx
> +![mocha side bar in Action](./mocha_side_bar.png)
Consider this resolved, see above thread, out of scope for this PR

2025-03-17 16:59 UTC, mark-wiemer commented on docs-next/src/content/docs/running/mocha_side_bar.png
Consider this resolved, see above thread, out of scope for this PR

2025-03-17 16:59 UTC, mark-wiemer commented on docs-next/src/content/docs/running/test-globs.mdx
> +See this [tutorial](https://gist.github.com/reggi/475793ea1846affbcfe8) on using globs.
Consider this resolved, good a11y candidate for followup PR

2025-03-17 17:00 UTC, mark-wiemer commented on docs-next/astro.config.ts
> +        { label: "Getting Started", slug: "getting-started" },
Honestly with the size of this PR it's a very low priority for me, maybe we can discuss later but Title Case is still pretty common and much better than ALL CAPS anyway :D

2025-03-17 17:41 UTC, JoshuaKGoldberg commented on docs-next/src/content/docs/index.mdx
> +If you see any **bugs** or **typos** _that aren't on [mochajs.org](https://mochajs.org)_, please mention them on [docs: add new website using Astro Starlight](https://github.com/mochajs/mocha/pull/52
Yeah make sense. I'll just remove it, since we're good to merge. 🚀

2025-03-17 18:18 UTC, merged

2025-03-17 18:54 UTC, mark-wiemer commented on docs-next/src/components/Badges.astro
> +    alt: "npm version",
Ref #5307

2025-03-17 18:55 UTC, mark-wiemer commented on docs-next/src/content/docs/declaring/dynamic-tests.mdx
> +// in suites ASYNCHRONOUS callbacks are NOT supported
Ref #5308

2025-03-17 19:22 UTC, mark-wiemer commented on docs-next/src/content/docs/running/editor-plugins.mdx
> +
Ref #5311