chore(deps): update choikdar to v4
mochajs/mocha pull request #5256
Opened 2024-11-16 10:04 UTC by ggodlewski

## PR Checklist

- [x ] Addresses an existing open issue: fixes #5214
- [ ] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Current chokidar is bundled with tons of spam deps including `braces` which trigger some audit alert.

All test are working. It supports globs unlike https://github.com/mochajs/mocha/pull/5215

2025-01-02 04:13 UTC, JoshuaKGoldberg requested changes
Hey thanks for getting this started! Sorry it took so long to review - since Chokidar didn't end up needing to be bumped with v11, this fell by the wayside. But I'm excited to help push this forward along now! 🚀 

Requesting changes primarily on a performance point, as well as a design point. Happy to talk if you want. 🙂

2025-01-02 04:13 UTC, JoshuaKGoldberg commented on lib/cli/watch-run.js
> +  const watchFilesFlat = [];
[Performance] This should be a `Set` so that lookups are an O(1) `.has()`, not an O(N) `.includes`. The `watchFilesFlat.includes(filePath)`s under `watcher.on('all', ...)` strike me as a likely hot path for repositories with many files.

2025-01-02 04:13 UTC, JoshuaKGoldberg commented on lib/cli/watch-run.js
> +      }
[Question] Is there a reason not to always regenerate if `event` is `'add`'? I.e.:

```js
watcher.on('all', (event, filePath) => {
  if (event === 'add') {
    regenerateWatchFilesFlat();
  }

  if (watchFilesFlat.includes(filePath)) {
    rerunner.scheduleRun();
  }
});
```

I think being able to deduplicate the code makes it a little clearer to read.

2025-01-02 04:13 UTC, JoshuaKGoldberg commented on lib/cli/watch-run.js
> +  regenerateWatchFilesFlat();
[Design] It took me a good amount of reading to figure out what's going on here. Summarizing how I understand it: `watchFilesFlat` is the persistent reference used under the `watcher.all('all', ...)` event. `regenerateWatchFilesFlat` is called on startup and whenever a file is added to regenerate that list of files, factoring in file and ignore globs. This used to be done by Chokidar v3 but is no longer done in Chokidar v4.

Proposal: I think this file is pretty long, and this area of logic is pretty insular to itself. What do you think about extracting it to a separate class or function? Vaguely:

```diff
- const watchFilesFlat = [];
+ const globFilesTracker = new GlobFilesTracker(watchFiles, watchIgnore);

...

- regenerateWatchFilesFlat();
+ globFilesTracker.regenerate();
```

...where maybe `GlobFilesTracker` is in a separate file and contains the logic to regenerate?

2025-01-02 12:41 UTC, ggodlewski commented
Hey @JoshuaKGoldberg, there is no way I remember the details after a month :). All I know it's been a struggle to get all tests working. In the meantime we switched to ava to resolve our issues, so I can't do much.
I updated the code to fix your issues. If there is anything that I can do fast let me know.

2025-01-02 12:41 UTC, ggodlewski commented on lib/cli/watch-run.js
> +  const watchFilesFlat = [];
I learnt something. Thanks.

2025-01-08 14:43 UTC, talentlessguy commented
@JoshuaKGoldberg is there any blocker to this PR besides merge conflicts of a lockfile?

2025-01-08 14:45 UTC, JoshuaKGoldberg commented
Just a re-request for review. I'll add it to the queue for review :)

2025-01-28 20:19 UTC, JoshuaKGoldberg requested changes
Source code looks good, thanks for the refactor!

I finally found time to really dig in and try this in production - and think I found a performance bug. LMK what you think of it.

2025-01-28 20:19 UTC, JoshuaKGoldberg commented on lib/cli/watch-run.js
[Bug] I tried this PR out on real-world code and found a performance issue from files being renamed. I found it on the ESLint codebase but also reproduced it in isolation here: https://github.com/JoshuaKGoldberg/repros/tree/mocha-chokidar-v4-pr-watching. Could you please take a look?

tl;dr: in a minimal codebase with two root-level test files, re-watching is reported as taking >200ms

2025-01-28 20:50 UTC, ggodlewski commented on lib/cli/watch-run.js
How exactly are you renaming the file? I run `mv b.test.js z.test.js` and I don't have the state with 0 passing:

```
$ node ../mocha/bin/mocha.js "*.test.js" --watch
  a
    ✔ passes
  b
    ✔ passes
  2 passing (2ms)

ℹ [mocha] waiting for changes...

  a
    ✔ passes
  b
    ✔ passes

  2 passing (1ms)

ℹ [mocha] waiting for changes...
```

2025-01-28 21:04 UTC, JoshuaKGoldberg commented on lib/cli/watch-run.js
Interesting. I did it through the VS Code UI. This is on an m1 Mac.

2025-01-29 09:22 UTC, ggodlewski commented on lib/cli/watch-run.js
I'm running Ubuntu. I have no hardware to reproduce it. It's strange because the `tracker.regenerate();` is only triggered on `event === 'add'`. I don't see how the list of files can be empty during rename of 1 file. Maybe you can add some debug output so we can trace the tracker method calls?

2025-01-30 16:13 UTC, JoshuaKGoldberg commented on lib/cli/watch-run.js
👍 added to the README.md. Interestingly, the long delay of ~200ms only happens if an `npm install` populated `node_modules/`. If you `rm -rf node_modules/` then the delay is only around 20-30ms.

2025-01-30 17:55 UTC, ggodlewski commented on lib/cli/watch-run.js
I added one more improvement. Glob should not traverse `node_modules`. Can you check if it improves anything?

2025-01-30 20:14 UTC, JoshuaKGoldberg commented on lib/cli/watch-run.js
💯 that fixed it for me! Back to 0-1ms  on the middle waiting.

+1 that it's a generalized solution too, not specific to `node_modules`. Nice 🙂

2025-01-30 20:18 UTC, JoshuaKGoldberg approved these changes
🔥 This is fantastic, thanks a bunch @ggodlewski! I really appreciate you sticking through & working with me on the reviews.

I've played with this a bunch locally on relatively small and large repros, and haven't found any issues. I'd really prefer to get another review from someone on @mochajs/maintenance-crew just to be safe - but otherwise ✅ on my end.

Nice job!

2025-01-30 20:18 UTC, JoshuaKGoldberg commented on lib/cli/watch-run.js
> +        ignored: () => false,
Despite the docs suggesting the object needs both `childrenIgnored` and `ignored`, I omitted `ignored` with no adverse effects locally. I think we can remove this?

```suggestion
```

2025-04-09 15:30 UTC, mark-wiemer commented
I'll take a look at this tonight :)

2025-04-10 01:38 UTC, mark-wiemer commented
@ggodlewski are you able to resolve the merge conflict? Otherwise looks great :)

2025-04-10 01:38 UTC, mark-wiemer approved these changes

2025-04-10 08:48 UTC, ggodlewski commented
@mark-wiemer I rebased against main and updated lock file.

2025-04-10 12:59 UTC, merged

2025-06-12 02:51 UTC, mark-wiemer commented on lib/cli/watch-run.js
> +  const watcher = chokidar.watch('.', {
@ggodlewski if you're available, I'm debugging #5355 and curious why we changed this to `watch('.'` from `watch(watchFiles`

2025-06-12 08:14 UTC, ggodlewski commented on lib/cli/watch-run.js
> +  const watcher = chokidar.watch('.', {
@mark-wiemer probably something related to removal of globs from v4. It has to start from some directory.
https://github.com/paulmillr/chokidar?tab=readme-ov-file#upgrading
I don't remember exactly, I'm guessing.

2025-06-13 00:52 UTC, mark-wiemer commented on lib/cli/watch-run.js
> +  const watcher = chokidar.watch('.', {
You're right, thanks :D the author of the mentioned incident linked the same stuff. Thanks for your patience, I'm still getting my bearings here :)