fix: improve error handling in global fixtures #5208
mochajs/mocha pull request #5275
Opened 2024-12-19 15:27 UTC by TG199

## PR Checklist

- [x] Addresses an existing open issue: fixes #5208
- [x] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md) were taken

## Overview
Description
This PR addresses an issue with the handling of errors in global teardown functions. Previously, if a global teardown function threw an error, the error was not logged clearly, and the process exit code might not reflect the failure.

Changes Made
Updated the _runGlobalFixtures method in lib/mocha.js to:
Log errors with a clear and descriptive message.
Set the process exit code to 1 when a global teardown function fails.
Improved debugging output to aid in identifying which function caused the error.
New Behavior
When a global teardown function fails:
A descriptive error message is logged.
The process exits with a non-zero code, signaling the failure.

2024-12-19 17:13 UTC, TG199 commented
All tests pass locally using npm run test-node:unit on both the main branch and my working branch. However, they fail in CI. This suggests an environment-specific issue. I'm investigating further and would appreciate any guidance on differences between the CI and local setups.

2025-01-02 05:24 UTC, JoshuaKGoldberg commented
> All tests pass locally using npm run test-node:unit on both the main branch and my working branch. However, they fail in CI. This suggests an environment-specific issue. I'm investigating further and would appreciate any guidance on differences between the CI and local setups.

Ah, this looks like #5278. Sorry for the confusing errors here - you can ignore them.

2025-01-02 05:30 UTC, JoshuaKGoldberg requested changes
A good start, thanks for sending this! I think there's some work to be done to flesh the PR out.

2025-01-02 05:30 UTC, JoshuaKGoldberg commented on lib/mocha.js
> +Mocha.prototype.passOnFailingTestSuite = function (passOnFailingTestSuite) {
This reminds me, I've been meaning to write a blog post about removing unrelated formatting changes from PRs... quick summary: unrelated changes clutter the Git history and make it harder to review PRs.

```suggestion
Mocha.prototype.passOnFailingTestSuite = function(passOnFailingTestSuite) {
```

At some point we'll start enforcing formatting in this repo anyway.

2025-01-02 05:30 UTC, JoshuaKGoldberg commented on lib/mocha.js
> +      console.error(err.stack);
[Functionality] This is a good start, but I think we'll want to do more than just log the error to the console. I think we'll want to mark the test as failed too. It's easy to miss console logs that don't change the exit code.

2025-01-02 05:30 UTC, JoshuaKGoldberg commented on lib/mocha.js
[Testing] This change is missing test coverage. It's great that existing tests pass, but there should be a test added that shows Mocha acting appropriately when an  a global fixture does reject.

2025-01-02 18:21 UTC, TG199 commented
Thanks for the review 🙏🏽. I'll make the necessary changes asap.

2025-01-28 20:05 UTC, JoshuaKGoldberg commented
👋 Just checking in @TG199, did you mean to [re-request review](https://github.blog/changelog/2019-02-21-re-request-review-on-a-pull-request/)?

2025-01-29 08:30 UTC, TG199 commented
Oh, actually yes, had no idea I could request for a review, thanks!

2025-01-30 16:07 UTC, JoshuaKGoldberg requested changes
Whenever tests are added, feel free to re-request review and I can take a look :)

2025-01-30 16:07 UTC, JoshuaKGoldberg commented on lib/mocha.js
@TG199 this is still an open piece of feedback, can you add tests please?

2025-02-06 08:18 UTC, TG199 commented
hi @JoshuaKGoldberg, need a little help here, I've been running into challenges trying to mark failed test. these are the different approaches I've tried:
First attempt - Trying to use runner.failures:

Mocha.prototype._runGlobalFixtures = async function _runGlobalFixtures(
  fixtureFns = [],
  context = {}
) {
  try {
    await fixtureFn.call(context);
  } catch (err) {
    console.error(err.stack);
    if (this.runner) {
      this.runner.failures++;
    }
    throw err;
  }
}
However, this.runner isn't available in this context 

Second attempt - Using a  fakeHook this.runner.failHook:

// In _runGlobalFixtures
if (this.runner) {
  const falseHook = new this._Hook("globalTeardown", "global teardown");
  this.runner.failHook(falseHook, err);
}
this is when I noticed this.runner is not available here. !!this.runner (logged: false)

Current attempt - Using a flag and run override:

Mocha.prototype._runGlobalFixtures = async function _runGlobalFixtures(
  fixtureFns = [],
  context = {},
) {
  for (const fixtureFn of fixtureFns) {
    try {
      await fixtureFn.call(context);
    } catch (err) {
      console.error('Global fixture error:', err.stack);
      this.globalTeardownErrored = true;
    }
  }
  return context;
};

const originalRun = Mocha.prototype.run;
Mocha.prototype.run = function (fn) {
  const self = this;
  return originalRun.call(this, (exitCode) => {
    const finalExitCode = exitCode > 0 || self.globalTeardownErrored ? 1 : 0;
    if (fn) fn(finalExitCode);
  });
};
This works for getting the exit code right, but I'm not sure if this is the best approach for integrating with Mocha's test reporting.
Questions:

What's the recommended way to access the runner or mark tests as failed from within _runGlobalFixtures?
Is there a better way to track these failures that would integrate better with Mocha's reporting system?
Should I be handling this at a different point in Mocha

Any guidance would be greatly appreciated! Thank you!

2025-02-06 13:12 UTC, JoshuaKGoldberg commented
Glad to see you're making progress on this! A couple quick tips to help me help you...

First, it's easier to read code snippets if you format code blocks as code. See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code. A lot easier to read 🙂 

Second, it's hard to help from just some standalone code. Can you try pushing your attempt(s) up as Git branches or commits? 

> What's the recommended way to access the runner or mark tests as failed from within _runGlobalFixtures?

Generally, the `context` parameter that it takes in. Although the docs on https://mochajs.org/api/mocha#globalTeardown -> https://mochajs.org/api/global#MochaGlobalFixture don't mention a parameter, you can see in code that it's given one:

https://github.com/mochajs/mocha/blob/deb8679810a60aa5198f49751f3d7b71e10fe072/lib/mocha.js#L1228-L1231

I also found this this by:

1. Putting a `console.log(new Error().stack)` in the global-fixture example's `mochaGlobalTeardown`: https://github.com/mochajs/mocha-examples/blob/48f723f4a6f28870ae1c49cffb74d228786b11e6/packages/global-fixture/fixture.js#L27: to see that it's called by `mocha/lib/mocha.js:1234`
2. Putting a `console.log(context)` in `mocha/lib/mocha.js:1234: to see what's in the context

> Is there a better way to track these failures that would integrate better with Mocha's reporting system?
Should I be handling this at a different point in Mocha

I'm not sure but it _seems_ reasonable to me to look there. `runGlobalTeardown` -> `_runGlobalFixtures` is the main pair of functions that calls the teardown fixtures. Either they or something that calls them would be a good place to try adding the logic.

Something to consider: `runGlobalTeardown` is specific to _teardown_; `_runGlobalFixtures` is for both _setup_ and _teardown_. Maybe that's a hint we should also handle _setup_ functions too? What if they error?

2025-02-06 19:10 UTC, TG199 commented
> Glad to see you're making progress on this! A couple quick tips to help me help you...
> 
> First, it's easier to read code snippets if you format code blocks as code. See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code. A lot easier to read 🙂
> 
> Second, it's hard to help from just some standalone code. Can you try pushing your attempt(s) up as Git branches or commits?
> 
> > What's the recommended way to access the runner or mark tests as failed from within _runGlobalFixtures?
> 
> Generally, the `context` parameter that it takes in. Although the docs on https://mochajs.org/api/mocha#globalTeardown -> https://mochajs.org/api/global#MochaGlobalFixture don't mention a parameter, you can see in code that it's given one:
> 
> https://github.com/mochajs/mocha/blob/deb8679810a60aa5198f49751f3d7b71e10fe072/lib/mocha.js#L1228-L1231
> 
> I also found this this by:
> 
> 1. Putting a `console.log(new Error().stack)` in the global-fixture example's `mochaGlobalTeardown`: https://github.com/mochajs/mocha-examples/blob/48f723f4a6f28870ae1c49cffb74d228786b11e6/packages/global-fixture/fixture.js#L27: to see that it's called by `mocha/lib/mocha.js:1234`
> 2. Putting a `console.log(context)` in `mocha/lib/mocha.js:1234: to see what's in the context
> 
> > Is there a better way to track these failures that would integrate better with Mocha's reporting system?
> > Should I be handling this at a different point in Mocha
> 
> I'm not sure but it _seems_ reasonable to me to look there. `runGlobalTeardown` -> `_runGlobalFixtures` is the main pair of functions that calls the teardown fixtures. Either they or something that calls them would be a good place to try adding the logic.
> 
> Something to consider: `runGlobalTeardown` is specific to _teardown_; `_runGlobalFixtures` is for both _setup_ and _teardown_. Maybe that's a hint we should also handle _setup_ functions too? What if they error?

2025-02-07 00:52 UTC, TG199 commented
> Glad to see you're making progress on this! A couple quick tips to help me help you...
> 
> First, it's easier to read code snippets if you format code blocks as code. See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code. A lot easier to read 🙂
>
I think I need to checkout Github docs more often
> Second, it's hard to help from just some standalone code. Can you try pushing your attempt(s) up as Git branches or commits?
> 
> > What's the recommended way to access the runner or mark tests as failed from within _runGlobalFixtures?
> 
> Generally, the `context` parameter that it takes in. Although the docs on https://mochajs.org/api/mocha#globalTeardown -> https://mochajs.org/api/global#MochaGlobalFixture don't mention a parameter, you can see in code that it's given one:
> 
> https://github.com/mochajs/mocha/blob/deb8679810a60aa5198f49751f3d7b71e10fe072/lib/mocha.js#L1228-L1231
> 
> I also found this this by:
> 
> 1. Putting a `console.log(new Error().stack)` in the global-fixture example's `mochaGlobalTeardown`: https://github.com/mochajs/mocha-examples/blob/48f723f4a6f28870ae1c49cffb74d228786b11e6/packages/global-fixture/fixture.js#L27: to see that it's called by `mocha/lib/mocha.js:1234`
> 2. Putting a `console.log(context)` in `mocha/lib/mocha.js:1234: to see what's in the context
>
Oh, okay, I try this out.
> > Is there a better way to track these failures that would integrate better with Mocha's reporting system?
> > Should I be handling this at a different point in Mocha
> 
> I'm not sure but it _seems_ reasonable to me to look there. `runGlobalTeardown` -> `_runGlobalFixtures` is the main pair of functions that calls the teardown fixtures. Either they or something that calls them would be a good place to try adding the logic.
> 
> Something to consider: `runGlobalTeardown` is specific to _teardown_; `_runGlobalFixtures` is for both _setup_ and _teardown_. Maybe that's a hint we should also handle _setup_ functions too? What if they error?
>
True, I'll keep that in mind, infinite thanks!

2025-02-07 21:54 UTC, TG199 commented
Hi @JoshuaKGoldberg will this do? 🙂

2025-02-16 22:10 UTC, JoshuaKGoldberg requested changes
Progress, thanks for continuing on this! 🚀

2025-02-16 22:10 UTC, JoshuaKGoldberg commented on lib/mocha.js
> + * Run global fixtures sequentially with context `context`.
Still some unrelated changes: a blank line above, this `.`, an extra `,` later, etc. - https://www.joshuakgoldberg.com/blog/split-out-unrelated-changes -> https://www.joshuakgoldberg.com/blog/split-out-unrelated-changes/#separate-logical-and-stylistic-changes

2025-02-16 22:10 UTC, JoshuaKGoldberg commented on test/integration/global-teardown-errors.spec.js
> +    await fs.mkdir(path.dirname(setupFile), { recursive: true });
[Refactor] Err, most fixture files are checked in to the repository. This would be the first instance in the `test/` directory of `fs.mkdir`. -1 from me on this strategy of writing test files dynamically and then removing them after the tests are done. Please switch to having fixtures checked in as regular files.

2025-02-16 22:10 UTC, JoshuaKGoldberg commented on lib/mocha.js
> +      if(context.stats) {
[Question] When would `context.stats` not exist?

I'm wondering if the parameters to the `_runGlobalFixtures` function can be assumed to exist. I.e. that the `= []` and `= {}` are unnecessary. I don't see any way in code to have them not exist.

2025-02-16 22:10 UTC, JoshuaKGoldberg commented on lib/mocha.js
> +  this.globalTeardownErrored = false;
[Refactor] Unused code?

```suggestion
```

2025-02-16 22:10 UTC, JoshuaKGoldberg commented on lib/mocha.js
> +        const isSetup = this.options.globalSetup && this.options.globalSetup.includes(fixtureFn);
[Refactor] Trying to query `this` properties to determine the phase is a little awkward: it's several lines of code and relies on other implementation details.

`_runGlobalFixtures` is called by places that know what phase they're in: `runGlobalTeardown` and `runGlobalSetup`. How about having them pass in the phase as an argument?

2025-02-16 22:10 UTC, JoshuaKGoldberg commented
> 👋 Just checking in @TG199, did you mean to [re-request review](https://github.blog/changelog/2019-02-21-re-request-review-on-a-pull-request/)?

Tip: I'm trying to convey a request to please use the re-request review when you'd like to. I get a lot of notifications and this helps me keep them organized. 🙂

2025-02-16 22:16 UTC, TG199 commented
Ohh, understood.

2025-02-20 15:23 UTC, JoshuaKGoldberg commented on test/integration/global-teardown-errors.spec.js
> +    await fs.mkdir(path.dirname(setupFile), { recursive: true });
@TG199 this piece of feedback is still open

2025-02-20 15:23 UTC, JoshuaKGoldberg commented on lib/mocha.js
> + * Run global fixtures sequentially with context `context`.
@TG199 this piece of feedback is still open

2025-02-20 15:25 UTC, JoshuaKGoldberg commented on lib/mocha.js
> +      process.exit(1);
[Bug] We can't manually `process.exit(1)` ourselves. Someone might be calling the Mocha API manually and expect to get results returned back to them. If you want to mark all tests as failed, you'll have to find another way.

2025-04-07 17:37 UTC, JoshuaKGoldberg commented
@TG199 did you mean to re-request review?

2025-04-10 01:59 UTC, mark-wiemer requested changes
Same changes requested as Josh, it's just those two active comments!

2025-05-06 01:25 UTC, closed without merging