chore: add "Thanks" section to release-please configuration
mochajs/mocha pull request #5276
Opened 2024-12-21 00:07 UTC by TG199

## PR Checklist

- [x] Addresses an existing open issue: fixes #000
- [x] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md) were taken

## Overview
Closes #5272

This PR modifies the release-please configuration to include contributor acknowledgments in our release notes, similar to typescript-eslint's format. This change will:

- Add a "Thank You" section at the bottom of release notes listing all contributors
- Keep the existing changelog sections and emojis
- Maintain clean, readable formatting of changes

2024-12-21 13:05 UTC, voxpelli commented
Can you give some reference to how this works? I wasn't aware that release-please could do this, so would love to know where I missed it

2024-12-23 19:16 UTC, TG199 commented
Oh hey Sir, unfortunately this doesn't work as expected, however, I'm trying out other methods like writing a script or creating a custom plugin for it.

2025-01-02 03:39 UTC, JoshuaKGoldberg commented on test/node-unit/reporters/parallel-buffered.spec.js
> +        expect(runner.listenerCount(EVENT_RUN_END), 'to equal', 0);
🤔 if there's something wrong with this test, it should be fixed in its own issue -> PR. Any CI failures also happening on `main` don't need to block or be fixed by this PR.

2025-01-02 03:43 UTC, JoshuaKGoldberg requested changes
I'm not sure if this is ready for review, but I have a design change request on it anyway. Posting now just in case it saves you some time going down a different path. Cheers!

2025-01-02 03:43 UTC, JoshuaKGoldberg commented on scripts/mention-contributors.mjs
[Change request] As a design point, I don't think taking on the burden of a full script is ideal. Assuming release-please doesn't have contribution thanks as a core feature, I think the next best thing would be a plugin. Which is a thing that can be made: https://github.com/googleapis/release-please/blob/3bae6137f939a4db2df1d32436453d1ac2a41e9f/docs/manifest-releaser.md#plugin-usage

https://github.com/googleapis/release-please/issues/2221 tracks them adding more docs and also links to some information + existing plugins.

Is that an approach you think could work?

2025-01-02 13:37 UTC, TG199 commented on test/node-unit/reporters/parallel-buffered.spec.js
> +        expect(runner.listenerCount(EVENT_RUN_END), 'to equal', 0);
Oh okay, got it.

2025-02-04 13:07 UTC, JoshuaKGoldberg commented
👋 Ping @TG199, is this still something you have time for?

2025-02-04 13:29 UTC, TG199 commented
Oh yes I do, sorry for keeping them open this long 🙏🏽

2025-02-09 11:09 UTC, TG199 commented on scripts/mention-contributors.mjs
Giving this a try!

2025-03-10 19:11 UTC, JoshuaKGoldberg commented
@TG199 how about we time box this to the end of this month?

2025-03-10 21:49 UTC, TG199 commented
> @TG199 how about we time box this to the end of this month?

I appreciate the check-in! I'll do my best to complete it by then, but if I run into any blockers, I'll update you, thanks.

2025-03-12 13:35 UTC, TG199 commented on scripts/mention-contributors.mjs
> [Change request] As a design point, I don't think taking on the burden of a full script is ideal. Assuming release-please doesn't have contribution thanks as a core feature, I think the next best thing would be a plugin. Which is a thing that can be made: https://github.com/googleapis/release-please/blob/3bae6137f939a4db2df1d32436453d1ac2a41e9f/docs/manifest-releaser.md#plugin-usage
> 
> [googleapis/release-please#2221](https://github.com/googleapis/release-please/issues/2221) tracks them adding more docs and also links to some information + existing plugins.
> 
> Is that an approach you think could work?

Hi,  considering the design point, would you prefer this as an internal plugin inside Mocha’s repo or an external plugin like release-please-ipfs-plugin? Since this is Mocha-specific, I’m leaning toward an internal plugin, but I’m open to whichever approach works best for Mocha.

2025-03-12 13:58 UTC, JoshuaKGoldberg commented on scripts/mention-contributors.mjs
Hmm, good question. I think the best case scenario would be an existing external plugin. Adding "thanks" to release-please release notes isn't really a Mocha-specific concern.  But if one doesn't yet exist it'd be easier to write it internally in the Mocha repo and iterate on it here for a bit. 👍 from me on an internal plugin for now.

2025-03-12 14:47 UTC, TG199 commented on scripts/mention-contributors.mjs
Alright, thanks

2025-04-07 17:37 UTC, JoshuaKGoldberg commented
Closing out as the timebox has passed. Thanks for sending though!

If anybody else has a working solution they can send a PR with that's ready for review, please do. And if it builds on code from this PR make sure to add a co-author attribution. Cheers! 🤎

2025-04-07 17:37 UTC, closed without merging

2025-04-07 19:06 UTC, TG199 commented
): okay, apologies on the delay 🙏🏽.